version: '3'

services:

  # Postgres database service
  # -------------------------------------------
  db:
    image: postgres:13
    restart: always
    volumes:
      - ${DOCKER_VOLUMES_LOCATION}/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"

  # Redis cache (used by nextcloud for lockfiles)
  # -------------------------------------------
  cache:
    image: redis:6
    restart: always
    command: --appendonly yes
    ports:
      - "6379"
    volumes:
      - ${DOCKER_VOLUMES_LOCATION}/cache:/data
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"

  # Nextcloud fpm application
  # -------------------------------------------
  app:
    image: nextcloud:21-fpm
    restart: always
    volumes:
      - ${DOCKER_VOLUMES_LOCATION}/app:/var/www/html
    environment:
      - REDIS_HOST=cache
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_DOMAIN}
      - TRUSTED_PROXIES=proxy
      - OVERWRITEPROTOCOL=https
      - SMTP_HOST=${NEXTCLOUD_SMTP_HOST}
      - SMTP_PORT=${NEXTCLOUD_SMTP_PORT}
      - SMTP_SECURE=${NEXTCLOUD_SMTP_SECURE}
      - SMTP_NAME=${NEXTCLOUD_SMTP_NAME}
      - SMTP_PASSWORD=${NEXTCLOUD_SMTP_PASSWORD}
      - MAIL_FROM_ADDRESS={NEXTCLOUD_MAIL_FROM_ADDRESS}
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
    depends_on:
      - db
      - cache

    # Cron jobs for Nextcloud
  # -------------------------------------------
  cron:
    image: nextcloud:21-fpm
    restart: always
    volumes:
      - ${DOCKER_VOLUMES_LOCATION}/app:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - cache

  # Nginx server for Nextcloud
  # -------------------------------------------
  web:
    image: nginx:1
    restart: always
    volumes:
      - ./config/web/nginx.conf:/etc/nginx/nginx.conf
      - ${DOCKER_VOLUMES_LOCATION}/app:/var/www/html:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.rule=HOST(`${NEXTCLOUD_DOMAIN}`)
      - traefik.http.routers.web.entrypoints=websecure
      - traefik.http.routers.web.middlewares=nextcloud,nextcloud_redirect
      - traefik.http.middlewares.nextcloud.headers.stsSeconds=15552001
      - traefik.http.middlewares.nextcloud.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.nextcloud.headers.stsPreload=true
      - traefik.http.middlewares.nextcloud_redirect.redirectregex.regex=/.well-known/(card|cal)dav
      - traefik.http.middlewares.nextcloud_redirect.redirectregex.replacement=/remote.php/dav/
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
    depends_on:
      - app
      - proxy

  # Traefick revers proxy: main entrypoint that handle https
  # -------------------------------------------
  proxy:
    image: traefik:2.4
    restart: always
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    volumes:
      - ./config/proxy/traefik.yml:/etc/traefik/traefik.yml
      - ${DOCKER_VOLUMES_LOCATION}/certificates:/certificates
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
