version: '3'

services:

  # Backup service
  # -------------------------------------------
  backup:
    image: blacklabelops/volumerize
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"

