version: '3'

services:

  # Google dynmic DNS polling solution
  # -------------------------------------------
  ddns:
    image: cwmr/google-domains-ddns 
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USERNAME=${GOOGLE_DDNS_USERNAME}
      - PASSWORD=${GOOGLE_DDNS_PASSWORD}
      - HOSTNAME=${GOOGLE_DDNS_HOSTNAME}
      - INTERVAL=${GOOGLE_DDNS_INTERVAL}
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "10"
